org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
kotlin.code.style=official
kotlin.stdlib.default.dependency=false
platformVersion=2026.1.1
pluginSinceBuild=261
aiAssistantPluginId=com.intellij.ml.llm
aiAssistantPluginVersion=261.23567.193
pluginPublishChannels=default
pluginVerifierIdeVersions=IU-2026.1.1
