org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
kotlin.code.style=official
kotlin.stdlib.default.dependency=false
platformReleaseLine=2026.2
platformVersion=2026.2.0.1
pluginSinceBuild=262
aiAssistantPluginId=com.intellij.ml.llm
aiAssistantPluginVersion=262.8665.344
pluginPublishChannels=default
pluginVerifierIdeVersions=IU-2026.2
integrationTestNettyVersion=4.2.16.Final
integrationTestJackson2Version=2.21.5
integrationTestJackson3Version=3.1.5
integrationTestOpenTelemetryVersion=1.62.0
integrationTestLz4Version=1.11.1
