org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
kotlin.code.style=official
kotlin.stdlib.default.dependency=false
platformVersion=2026.2.0.1
pluginSinceBuild=262
aiAssistantPluginId=com.intellij.ml.llm
aiAssistantPluginVersion=262.8665.344
pluginPublishChannels=default
pluginVerifierIdeVersions=IU-2026.2.0.1
